# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a16139755e3708c31c25723d120457695ad540f58a3c956256bd45a7458ae2174aa824c1f7f082b1a5627bf79bfbbd3bd9aa0ad43fdaad5b3168ef9785439f1

test:
  secret_key_base: 10f341afb97bcac15a45b29e03e89555e4e067e1e38fc2d6728aba72ecca93e9ba335a64ce4694a985d67fe62c80741f7ca33c42c4a049d777639a0f33a5ca33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
